version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
    groups:
      npm-production:
        dependency-type: production
      npm-development:
        dependency-type: development

  - package-ecosystem: pub
    directory: /apps/mobile/relax_app
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
