version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: digital-cigarette-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: digital_cigarette_break
    ports:
      - "5555:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: