const EXTRA_COZY_QUOTES = [
  ['Hôm nay chậm một chút cũng được. Cây lớn đâu có mọc bằng chế độ tăng tốc.', 'CALM'],
  ['Nếu lòng đang mỏi, đặt nó xuống cạnh mình. Không cần bế nó chạy cả ngày.', 'TIRED'],
  ['Bạn không cần chứng minh mình ổn để xứng đáng được thương.', 'SAD'],
  ['Một ngày khó không làm hỏng cả con đường. Nó chỉ là một đoạn nhiều ổ gà.', 'STRESSED'],
  ['Thở ra đi. Có vài thứ không cần giữ bằng vai.', 'ANXIOUS'],
  ['Bình thường không hề nhạt. Bình thường là nền nhà để mình đứng vững.', 'NEUTRAL'],
  ['Niềm vui nhỏ là một dạng vitamin. Uống đều, đừng xem thường.', 'HAPPY'],
  ['Có người đi cùng là tốt. Nhưng hôm nay tự đi chậm với mình cũng rất đáng khen.', 'LONELY'],
  ['Biết ơn một điều bé xíu cũng đủ mở hé cửa sổ trong lòng.', 'GRATEFUL'],
  ['Hào hứng thì cứ sáng lên. Đừng tự kéo rèm chỉ vì sợ người khác thấy.', 'EXCITED'],
  ['Bạn được phép bắt đầu lại bằng một việc rất nhỏ: uống nước, mở cửa sổ, hít sâu.', 'TIRED'],
  ['Không phải cảm xúc nào cũng cần kết luận. Có cái chỉ cần được đi ngang qua.', 'CALM'],
  ['Nếu hôm nay khó thương mình, hãy thử đối xử với mình như một người bạn thân.', 'SAD'],
  ['Căng thẳng không phải lệnh khẩn cấp cho cả đời. Nó chỉ là chuông báo cần nghỉ.', 'STRESSED'],
  ['Lo lắng đang cố bảo vệ bạn. Cảm ơn nó, rồi tự lái tiếp.', 'ANXIOUS'],
  ['Một phiên nghỉ không làm bạn tụt lại. Nó giúp bạn còn sức để quay lại.', 'TIRED'],
  ['Bạn không vô dụng. Bạn chỉ đang cần nạp lại phần mềm con người.', 'SAD'],
  ['Có những hôm thành tựu lớn nhất là không bỏ cuộc với chính mình.', 'NEUTRAL'],
  ['Đêm xuống rồi, não không cần mở thêm cuộc họp nào nữa.', 'CALM'],
  ['Nếu lòng như mưa, cứ tìm mái hiên trước. Tạnh hay chưa tính sau.', 'SAD'],
  ['Bạn không cần ôm hết mọi khả năng xấu để được gọi là chuẩn bị tốt.', 'ANXIOUS'],
  ['Bớt một việc hôm nay có thể là thêm một chút bình an cho ngày mai.', 'STRESSED'],
  ['Mọi thứ chưa xong không có nghĩa là bạn chưa đủ tốt.', 'NEUTRAL'],
  ['Cứ vui đi. Niềm vui không cần giấy phép.', 'HAPPY'],
  ['Bạn vẫn đáng được lắng nghe, kể cả khi chưa biết nói điều gì cho gọn.', 'LONELY'],
  ['Cảm ơn cơ thể vì vẫn đưa mình qua từng ngày, dù mình hay quên hỏi thăm nó.', 'GRATEFUL'],
  ['Năng lượng tốt đến thì mở cửa. Không cần đứng nghi ngờ ngoài hiên.', 'EXCITED'],
  ['Một hơi thở sâu là nút lưu tạm cho hệ thần kinh.', 'CALM'],
  ['Bạn có thể mềm mà vẫn mạnh. Gối mềm vẫn đỡ được một cái đầu mệt.', 'TIRED'],
  ['Không phải ai biến mất cũng là lỗi của bạn. Có người chỉ đi hết đoạn của họ.', 'SAD'],
  ['Đơn phương không làm tình cảm của bạn kém thật. Nó chỉ cần một nơi đặt xuống.', 'LONELY'],
  ['Tình yêu tốt không làm mình phải biến mất khỏi chính mình.', 'GRATEFUL'],
  ['Nếu cần vực dậy bản thân, bắt đầu bằng đứng dậy rót một ly nước thôi cũng tính.', 'TIRED'],
  ['Người kề bên đôi khi là chính mình phiên bản dịu hơn.', 'CALM'],
  ['Đêm mưa hợp để tha thứ cho việc hôm nay mình chưa hoàn hảo.', 'SAD'],
  ['Chữa lành không phải xoá sạch vết cũ. Là học cách không tự cào thêm.', 'SAD'],
  ['Có những thứ cần thời gian. Có những thứ cần ngủ một giấc.', 'TIRED'],
  ['Đừng để một tin nhắn chưa trả lời định nghĩa giá trị của bạn.', 'ANXIOUS'],
  ['Nếu tim đang chật, thử bỏ bớt một kỳ vọng không còn vừa.', 'STRESSED'],
  ['Bạn không cần trở thành ai khác để được bắt đầu yêu mình.', 'GRATEFUL'],
  ['Ngày mới không cần hoàn hảo. Nó chỉ cần một khe sáng để mình bước vào.', 'HAPPY'],
  ['Không ai bình tĩnh giỏi suốt. Mình chỉ tập quay về nhanh hơn một chút.', 'CALM'],
  ['Cứ đi chậm. Đường của mình không mở bằng đồng hồ của người khác.', 'NEUTRAL'],
  ['Mệt thì nghỉ. Không phải xin lỗi vì là con người.', 'TIRED'],
  ['Bạn không hề quá nhạy cảm. Có thể bạn chỉ nghe được những điều người khác bỏ qua.', 'SAD'],
  ['Khi đầu óc ồn, hãy chọn một âm thanh hiền hơn để đi theo.', 'ANXIOUS'],
  ['Một đoạn nhạc dịu có thể không sửa đời, nhưng có thể sửa nhịp thở lúc này.', 'CALM'],
  ['Có những ngày mình cần được ôm bằng lịch trống.', 'STRESSED'],
  ['Bạn đã sống sót qua rất nhiều ngày khó. Hôm nay mình tin thêm một ngày nữa.', 'GRATEFUL'],
  ['Không cần đi nhanh để gọi là tiến bộ. Đi tử tế với mình cũng là tiến bộ.', 'NEUTRAL'],
];

module.exports = {
  EXTRA_COZY_QUOTES,
};
