// @ts-nocheck
const { mkdir, readdir, readFile, writeFile } = require('node:fs/promises');
const path = require('node:path');

async function main() {
  const prismaDir = path.resolve(__dirname, '..');
  const schemaPartsDir = path.join(prismaDir, 'schema-parts');
  const outputPath = path.join(prismaDir, 'schema.prisma');

  const partFiles = (await readdir(schemaPartsDir))
    .filter((file) => file.endsWith('.prisma.part'))
    .sort((a, b) => a.localeCompare(b));

  const header = [
    '// This file is generated by prisma/scripts/build-schema.cjs.',
    '// Edit the source files in prisma/schema-parts/ instead of editing this file directly.',
    '',
  ].join('\n');

  const parts = await Promise.all(
    partFiles.map(async (file) => {
      const content = await readFile(path.join(schemaPartsDir, file), 'utf8');
      return content.trim();
    }),
  );

  await mkdir(prismaDir, { recursive: true });
  await writeFile(outputPath, `${header}${parts.join('\n\n')}\n`, 'utf8');

  console.log(
    `Built ${path.relative(process.cwd(), outputPath)} from ${partFiles.length} schema parts.`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
