import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:http/http.dart' as http;
import 'package:just_audio/just_audio.dart';

part 'app/relax_app.dart';
part 'config/env.dart';
part 'core/api_client.dart';
part 'core/session.dart';
part 'core/theme.dart';
part 'core/app_copy.dart';
part 'services/auth_service.dart';
part 'services/mood_service.dart';
part 'services/relax_session_service.dart';
part 'services/supabase_storage_service.dart';
part 'models/backend_models.dart';
part 'services/relax_catalog_service.dart';
part 'services/mobile_content_service.dart';
part 'screens/splash_screen.dart';
part 'screens/onboarding_screen.dart';
part 'screens/app_shell.dart';
part 'screens/home_screen.dart';
part 'screens/relax_screen.dart';
part 'screens/challenge_screen.dart';
part 'screens/setup_screen.dart';
part 'widgets/layout/app_scroll.dart';
part 'widgets/layout/header_bar.dart';
part 'widgets/navigation/pixel_bottom_nav.dart';
part 'widgets/pixel/pixel_panel.dart';
part 'widgets/pixel/pixel_badge.dart';
part 'widgets/common/section_title.dart';
part 'widgets/common/backend_status_banner.dart';
part 'widgets/common/page_dots.dart';
part 'widgets/common/speech_bubble.dart';
part 'widgets/buttons/pixel_button.dart';
part 'widgets/buttons/small_action_button.dart';
part 'widgets/buttons/pill_controls.dart';
part 'widgets/activity/activity_card.dart';
part 'widgets/mood/mood_tile.dart';
part 'widgets/mood/mood_progress.dart';
part 'widgets/mood/method_chip.dart';
part 'widgets/charts/mood_line_chart.dart';
part 'widgets/dashboard/stat_card.dart';
part 'widgets/dashboard/favorite_activity.dart';
part 'widgets/dashboard/mini_moment.dart';
part 'widgets/settings/setting_row.dart';
part 'widgets/settings/setting_action.dart';
part 'widgets/settings/time_chip.dart';
part 'widgets/cat/cat_widgets.dart';
part 'painters/pixel_scene_painter.dart';
part 'sheets/relax_sheets.dart';
part 'models/app_models.dart';

void main() {
  runApp(const RelaxApp());
}
