#!/usr/bin/env bash
# =============================================================================
# Cloudflare quick-tunnel for backend + web.
#
# Spins up two `cloudflared tunnel --url` quick tunnels (one per service),
# captures the auto-generated *.trycloudflare.com URLs, wires
#   apps/web/.env.local  ->  NEXT_PUBLIC_API_URL=<backend tunnel URL>
# so the web app — when restarted — talks to the backend through Cloudflare.
#
# Prereqs (script will *not* start them — they must already be running):
#   - backend  on http://localhost:${BACKEND_PORT:-6823}
#   - web      on http://localhost:${WEB_PORT:-3233}      (only if --web)
#   - apps/backend/.env has CORS_ORIGINS=*  (or include the web tunnel URL)
#
# Usage:
#   scripts/tunnel.sh            # backend + web tunnels (default)
#   scripts/tunnel.sh --backend  # backend only
#   scripts/tunnel.sh --web      # web only
#   BACKEND_PORT=7000 scripts/tunnel.sh
#
# Press Ctrl+C to stop all tunnels.
# =============================================================================

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_PORT="${BACKEND_PORT:-6823}"
WEB_PORT="${WEB_PORT:-3233}"

WANT_BACKEND=1
WANT_WEB=1
case "${1:-}" in
  --backend) WANT_WEB=0 ;;
  --web)     WANT_BACKEND=0 ;;
  --help|-h)
    sed -n '2,22p' "$0"
    exit 0
    ;;
  "") ;;
  *)
    echo "Unknown flag: $1 (use --backend, --web, or no flag for both)" >&2
    exit 2
    ;;
esac

BACKEND_LOG=""
WEB_LOG=""
BACKEND_PID=""
WEB_PID=""

cleanup() {
  echo ""
  echo "Stopping tunnels..."
  [[ -n "$BACKEND_PID" ]] && kill "$BACKEND_PID" 2>/dev/null || true
  [[ -n "$WEB_PID"     ]] && kill "$WEB_PID"     2>/dev/null || true
  [[ -n "$BACKEND_LOG" ]] && rm -f "$BACKEND_LOG"
  [[ -n "$WEB_LOG"     ]] && rm -f "$WEB_LOG"
}
trap cleanup EXIT INT TERM

# Wait up to 60s for `https://*.trycloudflare.com` to appear in the log.
extract_tunnel_url() {
  local log="$1"
  local label="$2"
  local url=""
  for _ in $(seq 1 60); do
    url="$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "$log" 2>/dev/null | head -1 || true)"
    if [[ -n "$url" ]]; then
      printf '%s' "$url"
      return 0
    fi
    sleep 1
  done
  echo "✗ Could not detect $label tunnel URL within 60s. Last log lines:" >&2
  tail -20 "$log" >&2
  return 1
}

port_listening() {
  local port="$1"
  lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
}

if (( WANT_BACKEND )); then
  if ! port_listening "$BACKEND_PORT"; then
    echo "⚠️  Nothing is listening on :$BACKEND_PORT — start the backend first (npm run dev:backend)" >&2
    exit 1
  fi
  BACKEND_LOG="$(mktemp -t cloudflared-backend.XXXXXX)"
  echo "→ Starting backend tunnel (localhost:$BACKEND_PORT)..."
  npx --yes cloudflared tunnel --no-autoupdate \
    --url "http://localhost:$BACKEND_PORT" >"$BACKEND_LOG" 2>&1 &
  BACKEND_PID=$!
  BACKEND_URL="$(extract_tunnel_url "$BACKEND_LOG" backend)"
  echo "✓ Backend tunnel: $BACKEND_URL"

  ENV_LOCAL="$ROOT/apps/web/.env.local"
  {
    echo "# Auto-generated by scripts/tunnel.sh on $(date '+%Y-%m-%d %H:%M:%S')"
    echo "# Restart the web dev server to pick up this change."
    echo "NEXT_PUBLIC_API_URL=$BACKEND_URL"
  } > "$ENV_LOCAL"
  echo "✓ Wrote $ENV_LOCAL (NEXT_PUBLIC_API_URL=$BACKEND_URL)"
fi

if (( WANT_WEB )); then
  if ! port_listening "$WEB_PORT"; then
    echo "⚠️  Nothing is listening on :$WEB_PORT — start the web app first (npm run dev:web)" >&2
    echo "    Hint: restart npm run dev:web *after* this script wrote apps/web/.env.local," >&2
    echo "    otherwise the dashboard still points at http://localhost:$BACKEND_PORT." >&2
    exit 1
  fi
  WEB_LOG="$(mktemp -t cloudflared-web.XXXXXX)"
  echo "→ Starting web tunnel (localhost:$WEB_PORT)..."
  npx --yes cloudflared tunnel --no-autoupdate \
    --url "http://localhost:$WEB_PORT" >"$WEB_LOG" 2>&1 &
  WEB_PID=$!
  WEB_URL="$(extract_tunnel_url "$WEB_LOG" web)"
  echo "✓ Web tunnel:     $WEB_URL"
fi

cat <<EOF

════════════════════════════════════════════════════════════════
 Cloudflare quick tunnels are live.

$( (( WANT_BACKEND )) && echo "   Backend (NestJS API)  →  ${BACKEND_URL:-}" )
$( (( WANT_WEB     )) && echo "   Web (Next.js)         →  ${WEB_URL:-}" )

 Reminders:
$( (( WANT_BACKEND )) && cat <<'NOTE'
   • apps/web/.env.local now points NEXT_PUBLIC_API_URL at the backend
     tunnel. Restart `npm run dev:web` so the dashboard picks it up.
   • Backend must accept the web tunnel origin in CORS. The easiest dev
     setup is CORS_ORIGINS=* in apps/backend/.env (dev only, not prod).
NOTE
)

 Press Ctrl+C to stop $( if (( WANT_BACKEND && WANT_WEB )); then echo "both tunnels"; else echo "the tunnel"; fi ).
════════════════════════════════════════════════════════════════

EOF

# Block until any child exits or Ctrl+C.
wait
