export const VI_SETTINGS_COPY = {
  defaultReminderTitle: 'Nhắc thở nhẹ',
  defaultReminderMessage: 'Đến lúc nghỉ một chút rồi hít thở nào.',
  companionTitle: 'Companion studio',
  companionCopy:
    'Đây là chỗ để anh nuôi, đặt tên và đổi linh thú theo ngày sinh, cung hoàng đạo, con giáp hoặc tự chọn.',
  noPreview: 'Chưa có preview',
  companionName: 'Tên linh thú',
  companionDefaultLabel: 'Linh thú',
  currentLevel: 'cấp độ hiện tại',
  affection: 'độ thân thiết',
  energy: 'năng lượng',
  renamedCompanion: 'Đã đổi tên linh thú',
  renameCompanionFailed: 'Không đổi được tên linh thú',
  saveName: 'Lưu tên',
  petted: 'Đã vuốt ve linh thú',
  fed: 'Đã cho linh thú ăn',
  played: 'Đã chơi với linh thú',
  interactFailed: 'Không tương tác được với linh thú',
  pet: 'Vuốt ve',
  feed: 'Cho ăn',
  play: 'Chơi',
  currentMode: 'mode đang áp dụng',
  currentMood: 'cảm xúc hiện tại',
  currentAction: 'trạng thái chuyển động',
  mappedBy: (key: string) => `Đang map theo ${key}`,
  customMode: 'Tự chọn linh thú theo ý anh',
  defaultMode: 'Dùng asset mặc định của hệ thống',
  changedMode: (mode: string) => `Đã chuyển sang ${mode}`,
  changeModeFailed: 'Không đổi được mode linh thú',
  selectAssetBelow: 'Chọn asset bên dưới',
  inUse: 'Đang dùng',
  apply: 'Áp dụng',
  applying: 'Đang áp dụng',
  syncedMode: (mode: string) => `Đã sync linh thú theo ${mode}`,
  syncModeFailed: 'Không đổi được linh thú theo mode này',
  customLibrary: 'Kho linh thú tự chọn',
  customLibraryCopy:
    'Đây là chỗ anh tự nạp linh thú cho profile hiện tại thay vì bị ràng theo cung hay con giáp.',
  companionPremiumTitle: 'Mode dành cho hội viên',
  companionPremiumBody:
    'Đổi linh thú theo cung hoàng đạo, 12 con giáp hoặc tự chọn dành cho gói hội viên tháng trở lên. Gói miễn phí vẫn dùng được linh thú mặc định.',
  loadedAsset: (name: string) => `Đã nạp linh thú ${name}`,
  loadAssetFailed: 'Không nạp được linh thú custom',
  assetFallbackDescription: 'Linh thú đồng hành',
  previewLoadFailed: 'Preview chưa tải được',
  companionLoading: 'Đang tải studio linh thú...',
  themeGalleryTitle: 'Theme gallery',
  themeGalleryCopy:
    'Chọn giao diện hợp mood của anh. Khi bấm áp dụng, app sẽ lưu mode và theme tương ứng vào preferences.',
  themeApplied: (name: string) => `Đã áp dụng theme ${name}`,
  themeApplyFailed: 'Không áp dụng được theme',
  systemDefaultSuffix: '• mặc định hệ thống',
  sessionsTitle: 'Thiết bị đăng nhập',
  sessionsCopy:
    'Theo dõi các phiên đã đăng nhập gần đây để biết tài khoản đang mở ở đâu.',
  currentSession: 'Phiên hiện tại',
  savedSession: 'Đã lưu',
  sessionsNote:
    'Bảng này đóng vai trò lịch sử đăng nhập. Cột Thiết bị chỉ hiển thị OS + dòng máy vì browser không cho phép app đọc tên máy thật (privacy). Muốn đặt tên thiết bị riêng, hãy đăng ký nó dưới mục Thiết bị push bên cạnh.',
  pushDevicesTitle: 'Thiết bị push',
  pushDevicesCopy:
    'Đăng ký nhanh trình duyệt hiện tại để test thông báo, hoặc gỡ những thiết bị không còn dùng nữa.',
  pushDeviceAdded: 'Đã thêm thiết bị web',
  pushDeviceAddedMessage:
    'Anh có thể dùng nó để test push/in-app notification ngay trong dashboard.',
  pushDeviceAddFailed: 'Không thêm được thiết bị',
  adding: 'Đang thêm',
  registerCurrentBrowser: 'Đăng ký trình duyệt này',
  pushDeviceRemoved: 'Đã gỡ thiết bị push',
  pushDeviceRemoveFailed: 'Không gỡ được thiết bị push',
  remove: 'Gỡ',
  remindersTitle: 'Nhắc nhở',
  remindersCopy:
    'Tạo các mốc nhắc mới, bật tắt nhanh hoặc xoá hẳn khi lịch sống của anh thay đổi.',
  titleLabel: 'Tiêu đề',
  typeLabel: 'Loại',
  datetimeLabel: 'Thời gian',
  reminderCreated: 'Đã tạo reminder',
  reminderCreatedMessage: (title: string) =>
    `"${title}" — lưu OK. Title giữ nguyên cho lần tạo tiếp.`,
  reminderCreateFailed: 'Tạo reminder thất bại',
  creating: 'Đang tạo',
  createReminder: 'Tạo reminder',
  savedReminderCount: (count: number) => `${count} nhắc đang lưu`,
  confirmDeleteAllReminders: (count: number) =>
    `Xoá tất cả ${count} nhắc? Hành động này không hoàn tác được.`,
  deletedReminderCount: (count: number) => `Đã xoá ${count} nhắc`,
  deleteAll: 'Xoá tất cả',
  scheduleLabel: 'Lịch',
  on: 'On',
  off: 'Off',
  reminderDisabled: 'Đã tắt reminder',
  reminderEnabled: 'Đã bật reminder',
  reminderStatusFailed: 'Không đổi được trạng thái reminder',
  disable: 'Tắt',
  enable: 'Bật',
  reminderDeleted: 'Đã xoá reminder',
  reminderDeleteFailed: 'Xoá reminder thất bại',
  billingTitle: 'Gói cước & nâng cấp',
  billingCopy:
    'Xem plan đang dùng và tạo checkout intent để backend ghi nhận nhu cầu nâng cấp.',
  currentPlan: 'Gói hiện tại',
  billingStatus: (status: string, renewal: string) =>
    `Trạng thái ${status} • gia hạn ${renewal}`,
  choosePlan: 'Chọn gói này',
  billingEmpty: 'Chưa tải được danh sách gói từ API billing.',
  activatedNote: (plan: string, status: string) =>
    `Đã kích hoạt gói ${plan}. Subscription chuyển sang ${status}.`,
  activatedTitle: (plan: string) => `Đã kích hoạt ${plan}`,
  activatedMessage: 'Thanh toán đã được xác nhận và gói đã được kích hoạt.',
  intentCreated: (plan: string) => `Đã tạo yêu cầu ${plan}`,
  intentRecorded: 'Backend đã ghi nhận checkout intent cho gói này.',
  upgradeFailed: 'Không hoàn tất được nâng cấp',
  upgradeFailedMessage: 'Kiểm tra backend billing rồi thử lại.',
  upgradeFailedReason: (reason: string) => `Lỗi từ server: ${reason}`,
  missingPaymentId:
    'Backend không trả về ID thanh toán — không thể kích hoạt gói. Báo dev kiểm tra /v1/billing/me/checkout-session.',
  redirectingToSepay: 'Đang chuyển tới cổng thanh toán SePay…',
  show: 'Hiển thị',
  sessionsPerPage: 'phiên / trang',
  previousPage: 'Trang trước',
  nextPage: 'Trang sau',
  reminderTime: 'Giờ nhắc',
  quickAddMessage: 'Nhắc nhẹ trong ngày từ Quick add.',
  quickAdded: (time: string) => `Đã thêm nhắc ${time}`,
  quickAddFailed: 'Không thêm được nhắc',
  quickAdd: 'Thêm nhanh',
  checkoutTitle: 'Tạo thanh khoản',
  checkoutCopy:
    'Xác nhận gói để backend tạo payment pending và trả trạng thái provider.',
  closeCheckout: 'Đóng checkout',
  upgradable: 'Có thể nâng cấp',
  intentReady: 'Backend đã tạo intent',
  paymentPendingNote:
    'Payment pending đã được ghi vào database. Khi cấu hình provider, chỗ này sẽ nhận checkout URL thật.',
  creatingIntent: 'Đang tạo intent',
  createCheckout: 'Tạo thanh khoản',
  modeZodiac: 'Theo cung hoàng đạo',
  modeChineseZodiac: 'Theo 12 con giáp',
  modeCustom: 'Tự chọn linh thú',
  modeDefault: 'Mặc định',
  free: 'Miễn phí',
  historyTitle: 'Lịch sử giao dịch',
  historyCopy: 'Lịch sử nạp tiền và nâng cấp gói cước.',
  colPlan: 'Gói',
  colAmount: 'Số tiền',
  colOrderCode: 'Mã đơn hàng',
  colTxCode: 'Mã giao dịch',
  colMethod: 'Cổng',
  colStatus: 'Trạng thái',
  colDate: 'Thời gian',
  statusSuccess: 'Thành công',
  statusPending: 'Đang chờ',
  statusFailed: 'Thất bại',
};

export const EN_SETTINGS_COPY: typeof VI_SETTINGS_COPY = {
  ...VI_SETTINGS_COPY,
  defaultReminderTitle: 'Gentle breathing reminder',
  defaultReminderMessage: 'Time to pause for a quick breath.',
  companionTitle: 'Companion studio',
  companionCopy:
    'Name, nurture and switch your companion by birthday, zodiac, Chinese zodiac or a custom pick.',
  noPreview: 'No preview yet',
  companionName: 'Companion name',
  companionDefaultLabel: 'Companion',
  currentLevel: 'current level',
  affection: 'affection',
  energy: 'energy',
  renamedCompanion: 'Companion renamed',
  renameCompanionFailed: 'Could not rename companion',
  saveName: 'Save name',
  petted: 'Companion petted',
  fed: 'Companion fed',
  played: 'Played with companion',
  interactFailed: 'Could not interact with companion',
  pet: 'Pet',
  feed: 'Feed',
  play: 'Play',
  currentMode: 'current mode',
  currentMood: 'current mood',
  currentAction: 'current action',
  mappedBy: (key: string) => `Mapped by ${key}`,
  customMode: 'Choose your own companion',
  defaultMode: 'Use the system default asset',
  changedMode: (mode: string) => `Switched to ${mode}`,
  changeModeFailed: 'Could not change companion mode',
  selectAssetBelow: 'Select an asset below',
  inUse: 'In use',
  apply: 'Apply',
  applying: 'Applying',
  syncedMode: (mode: string) => `Synced companion by ${mode}`,
  syncModeFailed: 'Could not switch companion for this mode',
  customLibrary: 'Custom companion library',
  customLibraryCopy:
    'Pick a custom companion for this profile instead of binding it to zodiac or Chinese zodiac.',
  companionPremiumTitle: 'Members-only mode',
  companionPremiumBody:
    'Picking by zodiac, Chinese zodiac or a custom asset is reserved for monthly subscribers and above. The default companion stays available on the free plan.',
  loadedAsset: (name: string) => `Loaded companion ${name}`,
  loadAssetFailed: 'Could not load custom companion',
  assetFallbackDescription: 'Companion buddy',
  previewLoadFailed: 'Preview could not load',
  companionLoading: 'Loading companion studio...',
  themeGalleryTitle: 'Theme gallery',
  themeGalleryCopy:
    'Choose a theme that matches your mood. Applying saves the matching mode and theme to preferences.',
  themeApplied: (name: string) => `Applied theme ${name}`,
  themeApplyFailed: 'Could not apply theme',
  systemDefaultSuffix: '• system default',
  sessionsTitle: 'Signed-in devices',
  sessionsCopy:
    'Review recent signed-in sessions and where the account is currently open.',
  currentSession: 'Current session',
  savedSession: 'Saved',
  sessionsNote:
    'This table is your login history. The Device column only shows OS and model because browsers do not expose the real device name for privacy. To set a friendly device name, register it under Push devices.',
  pushDevicesTitle: 'Push devices',
  pushDevicesCopy:
    'Register the current browser to test notifications, or remove devices you no longer use.',
  pushDeviceAdded: 'Web device added',
  pushDeviceAddedMessage:
    'You can use it to test push or in-app notifications from the dashboard.',
  pushDeviceAddFailed: 'Could not add device',
  adding: 'Adding',
  registerCurrentBrowser: 'Register this browser',
  pushDeviceRemoved: 'Push device removed',
  pushDeviceRemoveFailed: 'Could not remove push device',
  remove: 'Remove',
  remindersTitle: 'Reminders',
  remindersCopy:
    'Create reminder times, toggle them quickly or delete them when your routine changes.',
  titleLabel: 'Title',
  typeLabel: 'Type',
  datetimeLabel: 'Time',
  reminderCreated: 'Reminder created',
  reminderCreatedMessage: (title: string) =>
    `"${title}" was saved. The title stays for the next reminder.`,
  reminderCreateFailed: 'Could not create reminder',
  creating: 'Creating',
  createReminder: 'Create reminder',
  savedReminderCount: (count: number) => `${count} reminders saved`,
  confirmDeleteAllReminders: (count: number) =>
    `Delete all ${count} reminders? This cannot be undone.`,
  deletedReminderCount: (count: number) => `Deleted ${count} reminders`,
  deleteAll: 'Delete all',
  scheduleLabel: 'Schedule',
  on: 'On',
  off: 'Off',
  reminderDisabled: 'Reminder disabled',
  reminderEnabled: 'Reminder enabled',
  reminderStatusFailed: 'Could not update reminder status',
  disable: 'Disable',
  enable: 'Enable',
  reminderDeleted: 'Reminder deleted',
  reminderDeleteFailed: 'Could not delete reminder',
  billingTitle: 'Plans & upgrades',
  billingCopy:
    'Review the current plan and create a checkout intent so the backend records the upgrade request.',
  currentPlan: 'Current plan',
  billingStatus: (status: string, renewal: string) =>
    `Status ${status} • renews ${renewal}`,
  choosePlan: 'Choose this plan',
  billingEmpty: 'Could not load billing plans from the API.',
  activatedNote: (plan: string, status: string) =>
    `Activated ${plan}. Subscription moved to ${status}.`,
  activatedTitle: (plan: string) => `${plan} activated`,
  activatedMessage: 'Payment was confirmed and the plan was activated.',
  intentCreated: (plan: string) => `Created request for ${plan}`,
  intentRecorded: 'Backend recorded the checkout intent for this plan.',
  upgradeFailed: 'Could not complete upgrade',
  upgradeFailedMessage: 'Check backend billing and try again.',
  upgradeFailedReason: (reason: string) => `Server error: ${reason}`,
  missingPaymentId:
    'Backend did not return a payment id — cannot activate plan. Ask dev to check /v1/billing/me/checkout-session.',
  redirectingToSepay: 'Redirecting to SePay payment gateway…',
  show: 'Show',
  sessionsPerPage: 'sessions / page',
  previousPage: 'Previous page',
  nextPage: 'Next page',
  reminderTime: 'Reminder time',
  quickAddMessage: 'Quick daily reminder.',
  quickAdded: (time: string) => `Added reminder at ${time}`,
  quickAddFailed: 'Could not add reminder',
  quickAdd: 'Quick add',
  checkoutTitle: 'Create checkout intent',
  checkoutCopy:
    'Confirm the plan so the backend can create a pending payment and return provider status.',
  closeCheckout: 'Close checkout',
  upgradable: 'Upgradeable',
  intentReady: 'Backend created the intent',
  paymentPendingNote:
    'A pending payment was written to the database. Once a provider is configured, this area can receive a real checkout URL.',
  creatingIntent: 'Creating intent',
  createCheckout: 'Create intent',
  modeZodiac: 'By zodiac',
  modeChineseZodiac: 'By Chinese zodiac',
  modeCustom: 'Custom companion',
  modeDefault: 'Default',
  free: 'Free',
  historyTitle: 'Billing History',
  historyCopy: 'Transaction history for upgrades and deposits.',
  colPlan: 'Plan',
  colAmount: 'Amount',
  colOrderCode: 'Order Code',
  colTxCode: 'Tx Ref',
  colMethod: 'Gateway',
  colStatus: 'Status',
  colDate: 'Date',
  statusSuccess: 'Success',
  statusPending: 'Pending',
  statusFailed: 'Failed',
};
