export const userSelect = {
  id: true,
  email: true,
  name: true,
  avatar: true,
  role: true,
  authProvider: true,
  emailVerified: true,
  isActive: true,
  lastLoginAt: true,
  deletedAt: true,
  createdAt: true,
  updatedAt: true,
  profile: true,
  preferences: true,
  companion: {
    select: {
      id: true,
      name: true,
      type: true,
      mood: true,
      action: true,
      level: true,
      affection: true,
      energy: true,
      asset: {
        select: {
          id: true,
          name: true,
          type: true,
          key: true,
          chineseZodiac: true,
          zodiacSign: true,
          previewImageUrl: true,
          idleAnimationUrl: true,
        },
      },
    },
  },
  subscriptions: {
    orderBy: { createdAt: 'desc' },
    take: 1,
    select: {
      id: true,
      planName: true,
      status: true,
      endDate: true,
      tier: {
        select: {
          name: true,
        },
      },
    },
  },
} as const;
